Evaluate every per-node op-spec fixture derived from resnet18's real exported
graph (test/data/resnet18/, generated by bin/pt2_spec_gen from the model's own
tensor_values + real weight statistics — see .ai/pt2_node_spec_design.md)
through the real ATen kernel only (--eval: no native-engine comparison at
all). Each step prints the op's pretty-printed call, its output shape(s), and
a status. There is no external PyTorch ground truth to compare against, so
this committed/promoted output *is* the golden reference — a failure here
means the op's behavior (or its build) changed since the fixtures were
generated, not that the fixtures themselves are wrong.

  $ for f in data/resnet18/*.json; do ../bin/aten_spec_verify.exe --eval "$f"; done
  === data/resnet18/000_convolution_default.json ===
  [node] torch.ops.aten.convolution.default(input=f32[1,3,224,224]~normal(mean=0,variance=1), weight=f32[64,3,7,7]~normal(mean=2.94198e-05,variance=0.0168198), bias=none, stride=[2,2], padding=[3,3], dilation=[1,1], transposed=false, output_padding=[0,0], groups=1)
    -> out0: [1,64,112,112]
    status: ok
  === data/resnet18/001__native_batch_norm_legit_no_training_default.json ===
  [node] torch.ops.aten._native_batch_norm_legit_no_training.default(input=f32[1,64,112,112]~normal(mean=0,variance=1), weight=f32[64]~normal(mean=0.257577,variance=0.0149257), bias=f32[64]~normal(mean=0.18112,variance=0.0879732), running_mean=f32[64]~normal(mean=0.000847435,variance=0.00235273), running_var=f32[64]~uniform(low=1.0352e-13,high=13.7179), momentum=0.10000000149, eps=9.99999974738e-06)
    -> out0: [1,64,112,112]
    -> out1: [0]
    -> out2: [0]
    status: ok
  === data/resnet18/002_relu_default.json ===
  [node] torch.ops.aten.relu.default(self=f32[1,64,112,112]~normal(mean=0,variance=1))
    -> out0: [1,64,112,112]
    status: ok
  === data/resnet18/003_max_pool2d_with_indices_default.json ===
  [node] torch.ops.aten.max_pool2d_with_indices.default(self=f32[1,64,112,112]~normal(mean=0,variance=1), kernel_size=[3,3], stride=[2,2], padding=[1,1], dilation=[1], ceil_mode=false)
    -> out0: [1,64,56,56]
    -> out1: [1,64,56,56]
    status: ok
  === data/resnet18/004_convolution_default.json ===
  [node] torch.ops.aten.convolution.default(input=f32[1,64,56,56]~normal(mean=0,variance=1), weight=f32[64,64,3,3]~normal(mean=-0.00308705,variance=0.00285124), bias=none, stride=[1,1], padding=[1,1], dilation=[1,1], transposed=false, output_padding=[0,0], groups=1)
    -> out0: [1,64,56,56]
    status: ok
  === data/resnet18/005__native_batch_norm_legit_no_training_default.json ===
  [node] torch.ops.aten._native_batch_norm_legit_no_training.default(input=f32[1,64,56,56]~normal(mean=0,variance=1), weight=f32[64]~uniform(low=0.16826,high=0.64402), bias=f32[64]~normal(mean=-0.0341366,variance=0.0432284), running_mean=f32[64]~normal(mean=-0.904856,variance=0.786984), running_var=f32[64]~uniform(low=0.0671055,high=1.82797), momentum=0.10000000149, eps=9.99999974738e-06)
    -> out0: [1,64,56,56]
    -> out1: [0]
    -> out2: [0]
    status: ok
  === data/resnet18/006_relu_default.json ===
  [node] torch.ops.aten.relu.default(self=f32[1,64,56,56]~normal(mean=0,variance=1))
    -> out0: [1,64,56,56]
    status: ok
  === data/resnet18/007_convolution_default.json ===
  [node] torch.ops.aten.convolution.default(input=f32[1,64,56,56]~normal(mean=0,variance=1), weight=f32[64,64,3,3]~normal(mean=-0.000889332,variance=0.00204301), bias=none, stride=[1,1], padding=[1,1], dilation=[1,1], transposed=false, output_padding=[0,0], groups=1)
    -> out0: [1,64,56,56]
    status: ok
  === data/resnet18/008__native_batch_norm_legit_no_training_default.json ===
  [node] torch.ops.aten._native_batch_norm_legit_no_training.default(input=f32[1,64,56,56]~normal(mean=0,variance=1), weight=f32[64]~uniform(low=0.11363,high=0.624087), bias=f32[64]~normal(mean=0.00346287,variance=0.0398069), running_mean=f32[64]~normal(mean=-0.0646382,variance=0.0596178), running_var=f32[64]~uniform(low=0.0177301,high=0.305412), momentum=0.10000000149, eps=9.99999974738e-06)
    -> out0: [1,64,56,56]
    -> out1: [0]
    -> out2: [0]
    status: ok
  === data/resnet18/009_add_Tensor.json ===
  [node] torch.ops.aten.add.Tensor(self=f32[1,64,56,56]~normal(mean=0,variance=1), other=f32[1,64,56,56]~normal(mean=0,variance=1), alpha=1)
    -> out0: [1,64,56,56]
    status: ok
  === data/resnet18/010_relu_default.json ===
  [node] torch.ops.aten.relu.default(self=f32[1,64,56,56]~normal(mean=0,variance=1))
    -> out0: [1,64,56,56]
    status: ok
  === data/resnet18/011_convolution_default.json ===
  [node] torch.ops.aten.convolution.default(input=f32[1,64,56,56]~normal(mean=0,variance=1), weight=f32[64,64,3,3]~normal(mean=-0.00242004,variance=0.00258412), bias=none, stride=[1,1], padding=[1,1], dilation=[1,1], transposed=false, output_padding=[0,0], groups=1)
    -> out0: [1,64,56,56]
    status: ok
  === data/resnet18/012__native_batch_norm_legit_no_training_default.json ===
  [node] torch.ops.aten._native_batch_norm_legit_no_training.default(input=f32[1,64,56,56]~normal(mean=0,variance=1), weight=f32[64]~uniform(low=0.1831,high=0.46265), bias=f32[64]~normal(mean=-0.0835739,variance=0.0269769), running_mean=f32[64]~normal(mean=-0.61655,variance=0.725838), running_var=f32[64]~uniform(low=0.139254,high=1.06226), momentum=0.10000000149, eps=9.99999974738e-06)
    -> out0: [1,64,56,56]
    -> out1: [0]
    -> out2: [0]
    status: ok
  === data/resnet18/013_relu_default.json ===
  [node] torch.ops.aten.relu.default(self=f32[1,64,56,56]~normal(mean=0,variance=1))
    -> out0: [1,64,56,56]
    status: ok
  === data/resnet18/014_convolution_default.json ===
  [node] torch.ops.aten.convolution.default(input=f32[1,64,56,56]~normal(mean=0,variance=1), weight=f32[64,64,3,3]~normal(mean=-0.00126025,variance=0.00193384), bias=none, stride=[1,1], padding=[1,1], dilation=[1,1], transposed=false, output_padding=[0,0], groups=1)
    -> out0: [1,64,56,56]
    status: ok
  === data/resnet18/015__native_batch_norm_legit_no_training_default.json ===
  [node] torch.ops.aten._native_batch_norm_legit_no_training.default(input=f32[1,64,56,56]~normal(mean=0,variance=1), weight=f32[64]~uniform(low=0.0715255,high=0.760535), bias=f32[64]~normal(mean=-0.0299839,variance=0.0233957), running_mean=f32[64]~normal(mean=-0.0492384,variance=0.0445291), running_var=f32[64]~uniform(low=0.0169582,high=0.114688), momentum=0.10000000149, eps=9.99999974738e-06)
    -> out0: [1,64,56,56]
    -> out1: [0]
    -> out2: [0]
    status: ok
  === data/resnet18/016_add_Tensor.json ===
  [node] torch.ops.aten.add.Tensor(self=f32[1,64,56,56]~normal(mean=0,variance=1), other=f32[1,64,56,56]~normal(mean=0,variance=1), alpha=1)
    -> out0: [1,64,56,56]
    status: ok
  === data/resnet18/017_relu_default.json ===
  [node] torch.ops.aten.relu.default(self=f32[1,64,56,56]~normal(mean=0,variance=1))
    -> out0: [1,64,56,56]
    status: ok
  === data/resnet18/018_convolution_default.json ===
  [node] torch.ops.aten.convolution.default(input=f32[1,64,56,56]~normal(mean=0,variance=1), weight=f32[128,64,3,3]~normal(mean=-0.00145375,variance=0.00172914), bias=none, stride=[2,2], padding=[1,1], dilation=[1,1], transposed=false, output_padding=[0,0], groups=1)
    -> out0: [1,128,28,28]
    status: ok
  === data/resnet18/019__native_batch_norm_legit_no_training_default.json ===
  [node] torch.ops.aten._native_batch_norm_legit_no_training.default(input=f32[1,128,28,28]~normal(mean=0,variance=1), weight=f32[128]~uniform(low=0.162031,high=0.408659), bias=f32[128]~normal(mean=-0.0673463,variance=0.0118029), running_mean=f32[128]~normal(mean=-0.293953,variance=0.19124), running_var=f32[128]~uniform(low=0.144623,high=1.29844), momentum=0.10000000149, eps=9.99999974738e-06)
    -> out0: [1,128,28,28]
    -> out1: [0]
    -> out2: [0]
    status: ok
  === data/resnet18/020_relu_default.json ===
  [node] torch.ops.aten.relu.default(self=f32[1,128,28,28]~normal(mean=0,variance=1))
    -> out0: [1,128,28,28]
    status: ok
  === data/resnet18/021_convolution_default.json ===
  [node] torch.ops.aten.convolution.default(input=f32[1,128,28,28]~normal(mean=0,variance=1), weight=f32[128,128,3,3]~normal(mean=-0.00124767,variance=0.00115685), bias=none, stride=[1,1], padding=[1,1], dilation=[1,1], transposed=false, output_padding=[0,0], groups=1)
    -> out0: [1,128,28,28]
    status: ok
  === data/resnet18/022__native_batch_norm_legit_no_training_default.json ===
  [node] torch.ops.aten._native_batch_norm_legit_no_training.default(input=f32[1,128,28,28]~normal(mean=0,variance=1), weight=f32[128]~uniform(low=0.135804,high=0.617299), bias=f32[128]~normal(mean=-0.0035553,variance=0.00810078), running_mean=f32[128]~normal(mean=-0.199217,variance=0.0573569), running_var=f32[128]~uniform(low=0.0225368,high=0.243955), momentum=0.10000000149, eps=9.99999974738e-06)
    -> out0: [1,128,28,28]
    -> out1: [0]
    -> out2: [0]
    status: ok
  === data/resnet18/023_convolution_default.json ===
  [node] torch.ops.aten.convolution.default(input=f32[1,64,56,56]~normal(mean=0,variance=1), weight=f32[128,64,1,1]~normal(mean=-0.0025876,variance=0.00498669), bias=none, stride=[2,2], padding=[0,0], dilation=[1,1], transposed=false, output_padding=[0,0], groups=1)
    -> out0: [1,128,28,28]
    status: ok
  === data/resnet18/024__native_batch_norm_legit_no_training_default.json ===
  [node] torch.ops.aten._native_batch_norm_legit_no_training.default(input=f32[1,128,28,28]~normal(mean=0,variance=1), weight=f32[128]~normal(mean=0.195085,variance=0.010268), bias=f32[128]~normal(mean=-0.0035553,variance=0.00810078), running_mean=f32[128]~normal(mean=-0.0660763,variance=0.0940889), running_var=f32[128]~uniform(low=0.0057049,high=0.264434), momentum=0.10000000149, eps=9.99999974738e-06)
    -> out0: [1,128,28,28]
    -> out1: [0]
    -> out2: [0]
    status: ok
  === data/resnet18/025_add_Tensor.json ===
  [node] torch.ops.aten.add.Tensor(self=f32[1,128,28,28]~normal(mean=0,variance=1), other=f32[1,128,28,28]~normal(mean=0,variance=1), alpha=1)
    -> out0: [1,128,28,28]
    status: ok
  === data/resnet18/026_relu_default.json ===
  [node] torch.ops.aten.relu.default(self=f32[1,128,28,28]~normal(mean=0,variance=1))
    -> out0: [1,128,28,28]
    status: ok
  === data/resnet18/027_convolution_default.json ===
  [node] torch.ops.aten.convolution.default(input=f32[1,128,28,28]~normal(mean=0,variance=1), weight=f32[128,128,3,3]~normal(mean=-0.00153022,variance=0.00116761), bias=none, stride=[1,1], padding=[1,1], dilation=[1,1], transposed=false, output_padding=[0,0], groups=1)
    -> out0: [1,128,28,28]
    status: ok
  === data/resnet18/028__native_batch_norm_legit_no_training_default.json ===
  [node] torch.ops.aten._native_batch_norm_legit_no_training.default(input=f32[1,128,28,28]~normal(mean=0,variance=1), weight=f32[128]~uniform(low=0.198786,high=0.479532), bias=f32[128]~normal(mean=-0.21025,variance=0.0100913), running_mean=f32[128]~normal(mean=-0.295297,variance=0.108791), running_var=f32[128]~uniform(low=0.100834,high=0.510197), momentum=0.10000000149, eps=9.99999974738e-06)
    -> out0: [1,128,28,28]
    -> out1: [0]
    -> out2: [0]
    status: ok
  === data/resnet18/029_relu_default.json ===
  [node] torch.ops.aten.relu.default(self=f32[1,128,28,28]~normal(mean=0,variance=1))
    -> out0: [1,128,28,28]
    status: ok
  === data/resnet18/030_convolution_default.json ===
  [node] torch.ops.aten.convolution.default(input=f32[1,128,28,28]~normal(mean=0,variance=1), weight=f32[128,128,3,3]~normal(mean=-0.00127238,variance=0.000903057), bias=none, stride=[1,1], padding=[1,1], dilation=[1,1], transposed=false, output_padding=[0,0], groups=1)
    -> out0: [1,128,28,28]
    status: ok
  === data/resnet18/031__native_batch_norm_legit_no_training_default.json ===
  [node] torch.ops.aten._native_batch_norm_legit_no_training.default(input=f32[1,128,28,28]~normal(mean=0,variance=1), weight=f32[128]~uniform(low=0.0616608,high=0.650101), bias=f32[128]~normal(mean=-0.151284,variance=0.0188745), running_mean=f32[128]~normal(mean=-0.0601253,variance=0.0165077), running_var=f32[128]~uniform(low=0.0134403,high=0.0843676), momentum=0.10000000149, eps=9.99999974738e-06)
    -> out0: [1,128,28,28]
    -> out1: [0]
    -> out2: [0]
    status: ok
  === data/resnet18/032_add_Tensor.json ===
  [node] torch.ops.aten.add.Tensor(self=f32[1,128,28,28]~normal(mean=0,variance=1), other=f32[1,128,28,28]~normal(mean=0,variance=1), alpha=1)
    -> out0: [1,128,28,28]
    status: ok
  === data/resnet18/033_relu_default.json ===
  [node] torch.ops.aten.relu.default(self=f32[1,128,28,28]~normal(mean=0,variance=1))
    -> out0: [1,128,28,28]
    status: ok
  === data/resnet18/034_convolution_default.json ===
  [node] torch.ops.aten.convolution.default(input=f32[1,128,28,28]~normal(mean=0,variance=1), weight=f32[256,128,3,3]~normal(mean=-0.00136843,variance=0.000843744), bias=none, stride=[2,2], padding=[1,1], dilation=[1,1], transposed=false, output_padding=[0,0], groups=1)
    -> out0: [1,256,14,14]
    status: ok
  === data/resnet18/035__native_batch_norm_legit_no_training_default.json ===
  [node] torch.ops.aten._native_batch_norm_legit_no_training.default(input=f32[1,256,14,14]~normal(mean=0,variance=1), weight=f32[256]~uniform(low=0.217624,high=0.515868), bias=f32[256]~normal(mean=-0.114786,variance=0.00860034), running_mean=f32[256]~normal(mean=-0.324909,variance=0.107372), running_var=f32[256]~uniform(low=0.138049,high=0.774624), momentum=0.10000000149, eps=9.99999974738e-06)
    -> out0: [1,256,14,14]
    -> out1: [0]
    -> out2: [0]
    status: ok
  === data/resnet18/036_relu_default.json ===
  [node] torch.ops.aten.relu.default(self=f32[1,256,14,14]~normal(mean=0,variance=1))
    -> out0: [1,256,14,14]
    status: ok
  === data/resnet18/037_convolution_default.json ===
  [node] torch.ops.aten.convolution.default(input=f32[1,256,14,14]~normal(mean=0,variance=1), weight=f32[256,256,3,3]~normal(mean=-0.000786609,variance=0.000627303), bias=none, stride=[1,1], padding=[1,1], dilation=[1,1], transposed=false, output_padding=[0,0], groups=1)
    -> out0: [1,256,14,14]
    status: ok
  === data/resnet18/038__native_batch_norm_legit_no_training_default.json ===
  [node] torch.ops.aten._native_batch_norm_legit_no_training.default(input=f32[1,256,14,14]~normal(mean=0,variance=1), weight=f32[256]~uniform(low=0.185207,high=0.700149), bias=f32[256]~normal(mean=-0.0307664,variance=0.00785072), running_mean=f32[256]~normal(mean=-0.124856,variance=0.0238717), running_var=f32[256]~uniform(low=0.0414903,high=0.32787), momentum=0.10000000149, eps=9.99999974738e-06)
    -> out0: [1,256,14,14]
    -> out1: [0]
    -> out2: [0]
    status: ok
  === data/resnet18/039_convolution_default.json ===
  [node] torch.ops.aten.convolution.default(input=f32[1,128,28,28]~normal(mean=0,variance=1), weight=f32[256,128,1,1]~normal(mean=-0.00189588,variance=0.00108531), bias=none, stride=[2,2], padding=[0,0], dilation=[1,1], transposed=false, output_padding=[0,0], groups=1)
    -> out0: [1,256,14,14]
    status: ok
  === data/resnet18/040__native_batch_norm_legit_no_training_default.json ===
  [node] torch.ops.aten._native_batch_norm_legit_no_training.default(input=f32[1,256,14,14]~normal(mean=0,variance=1), weight=f32[256]~uniform(low=0.0236327,high=0.289002), bias=f32[256]~normal(mean=-0.0307664,variance=0.00785072), running_mean=f32[256]~normal(mean=-0.0469901,variance=0.00712728), running_var=f32[256]~uniform(low=0.00322833,high=0.0430159), momentum=0.10000000149, eps=9.99999974738e-06)
    -> out0: [1,256,14,14]
    -> out1: [0]
    -> out2: [0]
    status: ok
  === data/resnet18/041_add_Tensor.json ===
  [node] torch.ops.aten.add.Tensor(self=f32[1,256,14,14]~normal(mean=0,variance=1), other=f32[1,256,14,14]~normal(mean=0,variance=1), alpha=1)
    -> out0: [1,256,14,14]
    status: ok
  === data/resnet18/042_relu_default.json ===
  [node] torch.ops.aten.relu.default(self=f32[1,256,14,14]~normal(mean=0,variance=1))
    -> out0: [1,256,14,14]
    status: ok
  === data/resnet18/043_convolution_default.json ===
  [node] torch.ops.aten.convolution.default(input=f32[1,256,14,14]~normal(mean=0,variance=1), weight=f32[256,256,3,3]~normal(mean=-0.00166186,variance=0.000500012), bias=none, stride=[1,1], padding=[1,1], dilation=[1,1], transposed=false, output_padding=[0,0], groups=1)
    -> out0: [1,256,14,14]
    status: ok
  === data/resnet18/044__native_batch_norm_legit_no_training_default.json ===
  [node] torch.ops.aten._native_batch_norm_legit_no_training.default(input=f32[1,256,14,14]~normal(mean=0,variance=1), weight=f32[256]~uniform(low=0.139844,high=0.478451), bias=f32[256]~normal(mean=-0.237468,variance=0.0143435), running_mean=f32[256]~normal(mean=-0.390264,variance=0.113143), running_var=f32[256]~uniform(low=0.0674063,high=0.462863), momentum=0.10000000149, eps=9.99999974738e-06)
    -> out0: [1,256,14,14]
    -> out1: [0]
    -> out2: [0]
    status: ok
  === data/resnet18/045_relu_default.json ===
  [node] torch.ops.aten.relu.default(self=f32[1,256,14,14]~normal(mean=0,variance=1))
    -> out0: [1,256,14,14]
    status: ok
  === data/resnet18/046_convolution_default.json ===
  [node] torch.ops.aten.convolution.default(input=f32[1,256,14,14]~normal(mean=0,variance=1), weight=f32[256,256,3,3]~normal(mean=-0.00144139,variance=0.000427257), bias=none, stride=[1,1], padding=[1,1], dilation=[1,1], transposed=false, output_padding=[0,0], groups=1)
    -> out0: [1,256,14,14]
    status: ok
  === data/resnet18/047__native_batch_norm_legit_no_training_default.json ===
  [node] torch.ops.aten._native_batch_norm_legit_no_training.default(input=f32[1,256,14,14]~normal(mean=0,variance=1), weight=f32[256]~uniform(low=0.0491983,high=0.638344), bias=f32[256]~normal(mean=-0.163723,variance=0.022084), running_mean=f32[256]~normal(mean=-0.0833736,variance=0.0100527), running_var=f32[256]~uniform(low=0.005016,high=0.069144), momentum=0.10000000149, eps=9.99999974738e-06)
    -> out0: [1,256,14,14]
    -> out1: [0]
    -> out2: [0]
    status: ok
  === data/resnet18/048_add_Tensor.json ===
  [node] torch.ops.aten.add.Tensor(self=f32[1,256,14,14]~normal(mean=0,variance=1), other=f32[1,256,14,14]~normal(mean=0,variance=1), alpha=1)
    -> out0: [1,256,14,14]
    status: ok
  === data/resnet18/049_relu_default.json ===
  [node] torch.ops.aten.relu.default(self=f32[1,256,14,14]~normal(mean=0,variance=1))
    -> out0: [1,256,14,14]
    status: ok
  === data/resnet18/050_convolution_default.json ===
  [node] torch.ops.aten.convolution.default(input=f32[1,256,14,14]~normal(mean=0,variance=1), weight=f32[512,256,3,3]~normal(mean=-0.00156467,variance=0.000394956), bias=none, stride=[2,2], padding=[1,1], dilation=[1,1], transposed=false, output_padding=[0,0], groups=1)
    -> out0: [1,512,7,7]
    status: ok
  === data/resnet18/051__native_batch_norm_legit_no_training_default.json ===
  [node] torch.ops.aten._native_batch_norm_legit_no_training.default(input=f32[1,512,7,7]~normal(mean=0,variance=1), weight=f32[512]~uniform(low=0.137076,high=0.429307), bias=f32[512]~normal(mean=-0.225722,variance=0.00615779), running_mean=f32[512]~normal(mean=-0.408856,variance=0.0607061), running_var=f32[512]~uniform(low=0.0623902,high=0.296101), momentum=0.10000000149, eps=9.99999974738e-06)
    -> out0: [1,512,7,7]
    -> out1: [0]
    -> out2: [0]
    status: ok
  === data/resnet18/052_relu_default.json ===
  [node] torch.ops.aten.relu.default(self=f32[1,512,7,7]~normal(mean=0,variance=1))
    -> out0: [1,512,7,7]
    status: ok
  === data/resnet18/053_convolution_default.json ===
  [node] torch.ops.aten.convolution.default(input=f32[1,512,7,7]~normal(mean=0,variance=1), weight=f32[512,512,3,3]~normal(mean=-0.00130292,variance=0.00030015), bias=none, stride=[1,1], padding=[1,1], dilation=[1,1], transposed=false, output_padding=[0,0], groups=1)
    -> out0: [1,512,7,7]
    status: ok
  === data/resnet18/054__native_batch_norm_legit_no_training_default.json ===
  [node] torch.ops.aten._native_batch_norm_legit_no_training.default(input=f32[1,512,7,7]~normal(mean=0,variance=1), weight=f32[512]~uniform(low=0.140422,high=0.732236), bias=f32[512]~normal(mean=-0.197634,variance=0.00427759), running_mean=f32[512]~normal(mean=-0.143083,variance=0.00408457), running_var=f32[512]~uniform(low=0.01272,high=0.0900745), momentum=0.10000000149, eps=9.99999974738e-06)
    -> out0: [1,512,7,7]
    -> out1: [0]
    -> out2: [0]
    status: ok
  === data/resnet18/055_convolution_default.json ===
  [node] torch.ops.aten.convolution.default(input=f32[1,256,14,14]~normal(mean=0,variance=1), weight=f32[512,256,1,1]~normal(mean=-0.000843048,variance=0.0010747), bias=none, stride=[2,2], padding=[0,0], dilation=[1,1], transposed=false, output_padding=[0,0], groups=1)
    -> out0: [1,512,7,7]
    status: ok
  === data/resnet18/056__native_batch_norm_legit_no_training_default.json ===
  [node] torch.ops.aten._native_batch_norm_legit_no_training.default(input=f32[1,512,7,7]~normal(mean=0,variance=1), weight=f32[512]~normal(mean=0.250642,variance=0.00584434), bias=f32[512]~normal(mean=-0.197634,variance=0.00427759), running_mean=f32[512]~normal(mean=-0.0449821,variance=0.00613072), running_var=f32[512]~uniform(low=0.00319616,high=0.0676888), momentum=0.10000000149, eps=9.99999974738e-06)
    -> out0: [1,512,7,7]
    -> out1: [0]
    -> out2: [0]
    status: ok
  === data/resnet18/057_add_Tensor.json ===
  [node] torch.ops.aten.add.Tensor(self=f32[1,512,7,7]~normal(mean=0,variance=1), other=f32[1,512,7,7]~normal(mean=0,variance=1), alpha=1)
    -> out0: [1,512,7,7]
    status: ok
  === data/resnet18/058_relu_default.json ===
  [node] torch.ops.aten.relu.default(self=f32[1,512,7,7]~normal(mean=0,variance=1))
    -> out0: [1,512,7,7]
    status: ok
  === data/resnet18/059_convolution_default.json ===
  [node] torch.ops.aten.convolution.default(input=f32[1,512,7,7]~normal(mean=0,variance=1), weight=f32[512,512,3,3]~normal(mean=-0.0022611,variance=0.000317875), bias=none, stride=[1,1], padding=[1,1], dilation=[1,1], transposed=false, output_padding=[0,0], groups=1)
    -> out0: [1,512,7,7]
    status: ok
  === data/resnet18/060__native_batch_norm_legit_no_training_default.json ===
  [node] torch.ops.aten._native_batch_norm_legit_no_training.default(input=f32[1,512,7,7]~normal(mean=0,variance=1), weight=f32[512]~uniform(low=0.0969911,high=0.468488), bias=f32[512]~normal(mean=-0.24174,variance=0.0112342), running_mean=f32[512]~normal(mean=-0.595022,variance=0.0189681), running_var=f32[512]~uniform(low=0.0847953,high=0.272493), momentum=0.10000000149, eps=9.99999974738e-06)
    -> out0: [1,512,7,7]
    -> out1: [0]
    -> out2: [0]
    status: ok
  === data/resnet18/061_relu_default.json ===
  [node] torch.ops.aten.relu.default(self=f32[1,512,7,7]~normal(mean=0,variance=1))
    -> out0: [1,512,7,7]
    status: ok
  === data/resnet18/062_convolution_default.json ===
  [node] torch.ops.aten.convolution.default(input=f32[1,512,7,7]~normal(mean=0,variance=1), weight=f32[512,512,3,3]~normal(mean=-0.000107714,variance=0.000174276), bias=none, stride=[1,1], padding=[1,1], dilation=[1,1], transposed=false, output_padding=[0,0], groups=1)
    -> out0: [1,512,7,7]
    status: ok
  === data/resnet18/063__native_batch_norm_legit_no_training_default.json ===
  [node] torch.ops.aten._native_batch_norm_legit_no_training.default(input=f32[1,512,7,7]~normal(mean=0,variance=1), weight=f32[512]~uniform(low=1.5788,high=2.40754), bias=f32[512]~uniform(low=0.0722172,high=0.651092), running_mean=f32[512]~normal(mean=-0.0313929,variance=0.000407936), running_var=f32[512]~uniform(low=0.00951864,high=0.0308746), momentum=0.10000000149, eps=9.99999974738e-06)
    -> out0: [1,512,7,7]
    -> out1: [0]
    -> out2: [0]
    status: ok
  === data/resnet18/064_add_Tensor.json ===
  [node] torch.ops.aten.add.Tensor(self=f32[1,512,7,7]~normal(mean=0,variance=1), other=f32[1,512,7,7]~normal(mean=0,variance=1), alpha=1)
    -> out0: [1,512,7,7]
    status: ok
  === data/resnet18/065_relu_default.json ===
  [node] torch.ops.aten.relu.default(self=f32[1,512,7,7]~normal(mean=0,variance=1))
    -> out0: [1,512,7,7]
    status: ok
  === data/resnet18/066_mean_dim.json ===
  [node] torch.ops.aten.mean.dim(self=f32[1,512,7,7]~normal(mean=0,variance=1), dim=[-1,-2], keepdim=true)
    -> out0: [1,512,1,1]
    status: ok
  === data/resnet18/067_view_default.json ===
  [node] torch.ops.aten.view.default(self=f32[1,512,1,1]~normal(mean=0,variance=1), size=[1,512])
    -> out0: [1,512]
    status: ok
  === data/resnet18/068_permute_default.json ===
  [node] torch.ops.aten.permute.default(self=f32[1000,512]~normal(mean=5.85066e-08,variance=0.00482454), dims=[1,0])
    -> out0: [512,1000]
    status: ok
  === data/resnet18/069_addmm_default.json ===
  [node] torch.ops.aten.addmm.default(self=f32[1000]~normal(mean=-5.97377e-08,variance=0.000253469), mat1=f32[1,512]~normal(mean=0,variance=1), mat2=f32[512,1000]~normal(mean=0,variance=1), beta=1, alpha=1)
    -> out0: [1,1000]
    status: ok
