(* The in-process Wasm host in a browser: fixtures are generated by the
   JavaScript build of the compiler, compiled through the promise API (a main
   thread caps synchronous compilation of a large module) and run. The result
   is left on [globalThis.__wasm_probe] for the page's driver to read; nothing
   here touches node or the file system. *)
open Js_of_ocaml
open Graph_ir
open Loop_ir
module H = Loop_wasm_host

let tensor_of ~salt (sg : Tensor_sig.t) =
  let v c =
    float_of_int
      ((((Vec6.offset sg.Tensor_sig.shape c :> int) + salt) mod 7) - 3)
    /. 4.
  in
  Tensor.materialize sg.Tensor_sig.shape v

let bits t =
  let (Tensor.Tensor tt) = t in
  let acc = ref [] in
  Vec6.iter tt.Tensor.shape (fun c ->
      acc := Int32.bits_of_float (Tensor.read_at t (Vec6.get c)) :: !acc);
  List.rev !acc

let lines = Buffer.create 256
let say fmt = Format.kasprintf (fun s -> Buffer.add_string lines (s ^ "\n")) fmt

let finish () =
  Js.Unsafe.set Js.Unsafe.global "__wasm_probe"
    (Js.string (Buffer.contents lines))

let check name g k =
  let b =
    Err.or_raise ~pp_error:Loop_bundle.pp_error
      (Loop_bundle.build ~config:Loop_bundle_wasm.default_config g)
  in
  let sig_of id = Tensor_id.Map.find id g.Graph.tensors in
  let constants =
    List.map
      (fun id -> (id, tensor_of ~salt:3 (sig_of id)))
      b.Loop_bundle.constants
  in
  H.prepare_async b
    ~constants:(fun id -> List.assoc_opt id constants)
    (fun r ->
      (match Err.payload r with
      | Error e -> say "%s: prepare failed: %a" name H.pp_error e
      | Ok m ->
          let inputs =
            List.map
              (fun id -> (id, tensor_of ~salt:1 (sig_of id)))
              b.Loop_bundle.inputs
          in
          let reference =
            Err.or_raise ~pp_error:Eval_direct.pp_error
              (Eval_direct.run g ~constants ~inputs)
          in
          (match
             Err.payload (H.run m ~bind:(fun id -> List.assoc_opt id inputs))
           with
          | Error e -> say "%s: run failed: %a" name H.pp_error e
          | Ok outs ->
              say "%s: %s (%d bytes of module)" name
                (if
                   List.for_all2
                     (fun id t ->
                       bits t = bits (Tensor_id.Map.find id reference))
                     g.Graph.outputs outs
                 then "identical to the reference"
                 else "DIFFERS")
                (H.bundle_wasm m).Loop_bundle_wasm.stats
                  .Loop_bundle_wasm.module_bytes);
          H.dispose m);
      k ())

let () =
  let fixtures =
    [
      ("chain", Native_test.Graph_fixtures.chain ());
      ("residual", Native_test.Graph_fixtures.residual ());
      ("layer_norm", Native_test.Graph_fixtures.sink_permute_layer_norm ());
      ("sdpa", Native_test.Graph_fixtures.sink_permute_sdpa ());
    ]
  in
  let rec go = function
    | [] -> finish ()
    | (name, g) :: rest -> check name g (fun () -> go rest)
  in
  go fixtures
