(* Generator for the aten_op_walk.ml artifact: one random-walk module per curated
   op, emitted at generation time so the whole aten<->native bridge is covered.

   Driven by the same op list as aten_spec_gen (so it can't drift), each op is
   sorted into one of three tiers from its generated Op_<name> arg list:

   - Meta    : has a Walk_meta entry -> a full family-recipe walk.
   - Default : exactly one tensor arg and every other arg is fillable (optional
               -> None, or a renderable default) -> Recipe_default, which varies
               only the tensor's dim sizes (rank fixed). Valid but weaker.
   - Needs-meta : >=2 tensor args (correlated shapes) or a required non-tensor
               arg with no default -> no module; the target is collected into
               [needs_meta] so a coverage test prints the gap.

   Emits the per-op modules plus [all_walks] (the Meta+Default modules as
   first-class [Walk.Op] values) and [needs_meta]. *)

module Sg = Aten_spec_gen
module A = Aten_func_ast

let buf_add = Buffer.add_string

let is_tensor (k : Sg.kept) =
  match k.Sg.sty with Sg.T_tensor | Sg.T_tensor_opt -> true | _ -> false

let is_tensor_list (k : Sg.kept) =
  match k.Sg.sty with Sg.T_tensor_list -> true | _ -> false

(* A valid OCaml module name for a default-tier op's walk module. ocaml_name may
   start with '_' (e.g. _softmax), so prefix to guarantee an uppercase start. *)
let default_module_name (op : A.t) = "Walk_" ^ Sg.ocaml_name op

(* The fill expression for a non-tensor field in a default-tier record, or None
   if it can't be safely filled. We only fill an arg that has a concrete
   renderable default: an optional arg is left out of the default tier even when
   it nominally defaults to None, because per-arg None can still be an invalid
   *combination* (e.g. clamp rejects min=None & max=None) -- a cross-arg
   constraint no generic rule can see, so it belongs in walk_meta instead. *)
let fill_non_tensor (k : Sg.kept) : string option =
  if Sg.is_opt k.Sg.sty then None
  else
    match k.Sg.default with Some d -> Sg.dec_absent k.Sg.sty d | None -> None

(* The bound value for the single tensor field. *)
let tensor_binding (k : Sg.kept) =
  match k.Sg.sty with
  | Sg.T_tensor -> "t"
  | Sg.T_tensor_opt -> "Some t"
  | _ -> assert false

(* Emit a Meta-tier module from its Walk_meta entry. *)
let emit_meta buf (m : Walk_meta.t) =
  Printf.bprintf buf "module %s = struct\n" m.module_name;
  Printf.bprintf buf "  type cfg = Aten_walk_recipes.%s.t\n" m.recipe;
  buf_add buf "  type subject = Aten_spec.Op_spec.t\n\n";
  Printf.bprintf buf "  let target = %S\n" m.target;
  Printf.bprintf buf "  let initial = %s\n" m.initial;
  Printf.bprintf buf "  let axes = %s\n" m.axes;
  Printf.bprintf buf "  let cascade = Aten_walk_recipes.%s.cascade\n" m.recipe;
  Printf.bprintf buf "  let pp = Aten_walk_recipes.%s.pp\n\n" m.recipe;
  buf_add buf "  let build pcg c =\n";
  buf_add buf "    let open Aten_walk_recipes in\n";
  Printf.bprintf buf "    %s\n" m.build;
  buf_add buf "end\n\n"

(* Emit a Default-tier module: vary the lone tensor's shape, hold scalars at
   their defaults. [tk] is the tensor arg; [kept] are all record fields. *)
let emit_default buf (op : A.t) (kept : Sg.kept list) (tk : Sg.kept) =
  let name = default_module_name op in
  let op_mod = Sg.module_name op in
  let field (k : Sg.kept) =
    let v =
      if k == tk then tensor_binding k
      else match fill_non_tensor k with Some e -> e | None -> assert false
    in
    Printf.sprintf "%s = %s" k.Sg.id v
  in
  let fields = String.concat "; " (List.map field kept) in
  Printf.bprintf buf "module %s = struct\n" name;
  buf_add buf "  type cfg = Aten_walk_recipes.Recipe_default.t\n";
  buf_add buf "  type subject = Aten_spec.Op_spec.t\n\n";
  Printf.bprintf buf "  let target = %S\n" (Sg.target op);
  buf_add buf
    "  let initial = Aten_walk_recipes.Recipe_default.{ shape = [ 2; 3; 4; 4 ] }\n";
  buf_add buf "  let axes = Aten_walk_recipes.Recipe_default.axes\n";
  buf_add buf "  let cascade = Aten_walk_recipes.Recipe_default.cascade\n";
  buf_add buf "  let pp = Aten_walk_recipes.Recipe_default.pp\n\n";
  buf_add buf "  let build pcg c =\n";
  buf_add buf "    let open Aten_walk_recipes in\n";
  buf_add buf
    "    let t, pcg = Walk.tensor_spec pcg (Recipe_default.shape c) in\n";
  Printf.bprintf buf "    (Aten_op_spec.%s.(spec { %s }), pcg)\n" op_mod fields;
  buf_add buf "end\n\n"

(* Decide a default-tier op's tensor arg, or None if it isn't eligible. *)
let default_tensor (kept : Sg.kept list) : Sg.kept option =
  if List.exists is_tensor_list kept then None
  else
    match List.filter is_tensor kept with
    | [ tk ] ->
        let others = List.filter (fun k -> not (k == tk)) kept in
        if List.for_all (fun k -> fill_non_tensor k <> None) others then Some tk
        else None
    | _ -> None

let banner =
  {|(* @generated by aten_walk_gen (bin/aten_ops_gen.ml) from native_functions.yaml
   and lib/aten_gen/walk_meta.ml. DO NOT EDIT. Regenerate via lib/aten_op_walk/dune. *)|}

let file (ops : A.t list) =
  let buf = Buffer.create 8192 in
  buf_add buf banner;
  buf_add buf "\n\n";
  (* (module_name, target) for each emitted Meta/Default module, in op order. *)
  let walks = ref [] in
  let needs_meta = ref [] in
  let meta_hits = ref [] in
  List.iter
    (fun op ->
      match Sg.kept_args op with
      | None -> () (* no generated spec to build on *)
      | Some kept -> (
          let target = Sg.target op in
          match Walk_meta.find target with
          | Some m ->
              emit_meta buf m;
              meta_hits := target :: !meta_hits;
              walks := m.module_name :: !walks
          | None -> (
              match default_tensor kept with
              | Some tk ->
                  emit_default buf op kept tk;
                  walks := default_module_name op :: !walks
              | None -> needs_meta := target :: !needs_meta)))
    ops;
  (* Drift guard: every Walk_meta entry must have matched a curated op. *)
  List.iter
    (fun (m : Walk_meta.t) ->
      if not (List.mem m.target !meta_hits) then
        failwith
          (Printf.sprintf "walk_meta: target %S matches no curated op" m.target))
    Walk_meta.entries;
  let walks = List.rev !walks in
  let needs_meta = List.rev !needs_meta in
  buf_add buf
    {|let all_walks :
    (module Aten_walk_recipes.Walk.Op with type subject = Aten_spec.Op_spec.t)
    list =
  [
|};
  List.iter
    (fun name ->
      Printf.bprintf buf
        "    (module %s : Aten_walk_recipes.Walk.Op with type subject = \
         Aten_spec.Op_spec.t);\n"
        name)
    walks;
  buf_add buf "  ]\n\n";
  buf_add buf "let needs_meta : string list =\n  [\n";
  List.iter (fun t -> Printf.bprintf buf "    %S;\n" t) needs_meta;
  buf_add buf "  ]\n";
  Buffer.contents buf
