(* File assembly: turn an ordered list of per-op [Gen.generated] records into
   the three complete artifacts that lib/aten compiles and binds against:

     atg_ops.h                extern "C" declarations  (the C ABI surface)
     atg_ops.cpp              extern "C" definitions   (each calls at::<op>)
     operation_description.ml the ctypes Functions functor (one [foreign] line)

   These mirror the previously hand-written files; the per-op bodies come
   straight from [Gen], this module only supplies the surrounding boilerplate.
   Every file carries a do-not-edit banner since they are build-tree artifacts.
   Each op is preceded by a comment with its source schema signature.

   Output is assembled with the Format module: each artifact is one
   [Format.asprintf] over a fixed skeleton, with the repeated op section printed
   by [pp_print_list]. The banners and the generated fragments travel as %s/%a
   arguments (never as format-string text) so their [@generated] / [@->] stay
   literal rather than being read as Format directives. *)

let banner =
  {|/* @generated by aten_gen (bin/aten_ops_gen.ml) from native_functions.yaml.
   DO NOT EDIT. Regenerate via the dune rules in lib/aten/dune. */|}

let ml_banner =
  {|(* @generated by aten_gen (bin/aten_ops_gen.ml) from native_functions.yaml.
   DO NOT EDIT. Regenerate via the dune rules in lib/aten/dune. *)|}

(* op-section separators for [pp_print_list]: one blank line between C decls/
   defs, a paragraph break between ctypes bindings. *)
let blank_line ppf () = Format.fprintf ppf "\n"
let paragraph ppf () = Format.fprintf ppf "\n\n"

let header ops =
  let pp_decl ppf (g : Gen.generated) =
    Format.fprintf ppf "/* %s */\n%s\n" g.signature g.c_decl
  in
  Format.asprintf
    {|%s

#ifndef ATG_OPS_H_
#define ATG_OPS_H_

#include "atg_shim.h" /* atc_tensor + C scalar/handle types */

#ifdef __cplusplus
extern "C" {
#endif

%a
#ifdef __cplusplus
}
#endif

#endif /* ATG_OPS_H_ */
|}
    banner
    (Format.pp_print_list ~pp_sep:blank_line pp_decl)
    ops

let source ops =
  let pp_def ppf (g : Gen.generated) =
    Format.fprintf ppf "/* %s */\n%s\n" g.signature g.c_source
  in
  Format.asprintf
    {|%s

#include "atg_ops.h"

#include <ATen/Functions.h>

extern "C" {

%a
}  // extern "C"
|}
    banner
    (Format.pp_print_list ~pp_sep:blank_line pp_def)
    ops

let ocaml ops =
  let pp_binding ppf (g : Gen.generated) =
    Format.fprintf ppf "  (* %s *)\n  %s" g.signature g.ctypes_line
  in
  Format.asprintf
    {|%s

open Ctypes

(* The opaque tensor handle is shared with the Tensor API so a tensor from
   [C.Functions.new_] can be passed straight into these ops. *)
let atc_tensor = Function_description.atc_tensor

(* Multi-output op result structs, declared in Type_description.Types and filled
   through an out-param by a status-returning op (see Gen). Read output [field]
   with [tensors_get] (an owning handle the caller must free). *)
let tensors2_struct = Types_generated.tensors2_struct
let tensors3_struct = Types_generated.tensors3_struct
let tensors_get s field = getf s field

(* c10 enum args cross the C ABI as their integer code; these ctypes views give
   the OCaml side the typed [Scalar_type.t] enum instead of a bare int. An
   optional enum uses a negative sentinel for None (nullopt in C++). *)
let scalar_type =
  view int
    ~read:(fun i ->
      match Scalar_type.of_int i with
      | Some s -> s
      | None -> Printf.ksprintf failwith "unknown ScalarType code %%d" i)
    ~write:Scalar_type.to_int

let scalar_type_opt =
  view int
    ~read:(fun i -> if i < 0 then None else Scalar_type.of_int i)
    ~write:(function None -> -1 | Some s -> Scalar_type.to_int s)

let memory_format =
  view int
    ~read:(fun i ->
      match Memory_format.of_int i with
      | Some m -> m
      | None -> Printf.ksprintf failwith "unknown MemoryFormat code %%d" i)
    ~write:Memory_format.to_int

let memory_format_opt =
  view int
    ~read:(fun i -> if i < 0 then None else Memory_format.of_int i)
    ~write:(function None -> -1 | Some m -> Memory_format.to_int m)

let layout_opt =
  view int
    ~read:(fun i -> if i < 0 then None else Layout.of_int i)
    ~write:(function None -> -1 | Some l -> Layout.to_int l)

(* bool? : the 0/1 value with a negative sentinel for None (mirrors the enum
   optionals). [bool_opt] is the ctypes view over [bool option]. *)
let bool_opt =
  view int
    ~read:(fun i -> if i < 0 then None else Some (i <> 0))
    ~write:(function None -> -1 | Some b -> if b then 1 else 0)

(* c10::Scalar crosses as [struct atc_scalar] (declared in Type_description.Types
   so the stub generator binds it to atg_shim.h), passed by pointer — a by-value
   struct arg makes the generator re-emit a conflicting definition. [scalar] /
   [scalar_opt] views marshal the typed [Scalar.t] union (and its option). *)
let scalar_value_of = function
  | Scalar.Int i ->
      let v = make Types_generated.scalar_value in
      setf v Types_generated.value_i i;
      v
  | Scalar.Float d ->
      let v = make Types_generated.scalar_value in
      setf v Types_generated.value_d d;
      v
  | Scalar.Bool b ->
      let v = make Types_generated.scalar_value in
      setf v Types_generated.value_b b;
      v

(* Allocate a [struct atc_scalar] with the given tag and (optional) payload, and
   return a pointer to it (kept alive by the GC for the duration of the call). *)
let scalar_ptr (tag : Scalar.Tag.t) value =
  let s = make Types_generated.scalar_struct in
  setf s Types_generated.scalar_tag (Scalar.Tag.to_int tag);
  Option.iter (fun v -> setf s Types_generated.scalar_v v) value;
  allocate Types_generated.scalar_struct s

let scalar_read p =
  let s = !@p in
  let v = getf s Types_generated.scalar_v in
  match Scalar.Tag.of_int (getf s Types_generated.scalar_tag) with
  | Scalar.Tag.Int -> Scalar.Int (getf v Types_generated.value_i)
  | Scalar.Tag.Float -> Scalar.Float (getf v Types_generated.value_d)
  | Scalar.Tag.Bool -> Scalar.Bool (getf v Types_generated.value_b)
  | Scalar.Tag.None_ -> failwith "scalar view: NONE tag for a present scalar"

let scalar =
  view
    (ptr Types_generated.scalar_struct)
    ~read:scalar_read
    ~write:(fun sc -> scalar_ptr (Scalar.tag sc) (Some (scalar_value_of sc)))

let scalar_opt =
  view
    (ptr Types_generated.scalar_struct)
    ~read:(fun p ->
      if Scalar.Tag.of_int (getf !@p Types_generated.scalar_tag) = Scalar.Tag.None_
      then None
      else Some (scalar_read p))
    ~write:(function
      | None -> scalar_ptr Scalar.Tag.None_ None
      | Some sc -> scalar_ptr (Scalar.tag sc) (Some (scalar_value_of sc)))

(* c10::Device crosses as [struct atc_device] (declared in Type_description.Types)
   by pointer, like Scalar. [device] / [device_opt] views marshal the typed
   [Device.t] (and its option); a negative type code encodes an absent Device?. *)
let device_ptr type_code index =
  let s = make Types_generated.device_struct in
  setf s Types_generated.device_type_code type_code;
  setf s Types_generated.device_index index;
  allocate Types_generated.device_struct s

let device_read p =
  let s = !@p in
  let code = getf s Types_generated.device_type_code in
  match Device.Type.of_int code with
  | Some t -> { Device.type_ = t; index = getf s Types_generated.device_index }
  | None -> Printf.ksprintf failwith "device view: unknown DeviceType code %%d" code

let device =
  view
    (ptr Types_generated.device_struct)
    ~read:device_read
    ~write:(fun (d : Device.t) ->
      device_ptr (Device.Type.to_int d.type_) d.index)

let device_opt =
  view
    (ptr Types_generated.device_struct)
    ~read:(fun p ->
      if getf !@p Types_generated.device_type_code < 0 then None
      else Some (device_read p))
    ~write:(function
      | None -> device_ptr (-1) 0
      | Some (d : Device.t) -> device_ptr (Device.Type.to_int d.type_) d.index)

(* dune's ctypes requires the functor module to be named [Functions]; the
   [(instance Operations)] stanza aliases it to [C.Operations]. *)
module Functions (F : Ctypes.FOREIGN) = struct
  open F

%a
end
|}
    ml_banner
    (Format.pp_print_list ~pp_sep:paragraph pp_binding)
    ops
